### PR TITLE
Fixes name collision between hclust.jl and HClust.jl in OSX checkout process

### PR DESCRIPTION
**Pull request by slundberg**
hclust.jl overwrites HClust.jl when doing a package install on OSX. This fixes that by renaming hclust.jl to hclust_impl.jl and allows the package to work on OSX.

### CODE REVIEW

**Comment by davidavdav** [comment]
See [this rant](http://www.itworld.com/article/2868393/linus-torvalds-apples-hfs-is-probably-the-worst-file-system-ever.html), to which I wholeheartedly agree.  This policy recently costed me a day reinstalling a new mac, and caused me to lose backup history on two independent backups.  

BTW I have a pull request to [include this in Clustering](https://github.com/JuliaStats/Clustering.jl/pull/32), but it seems kind-of dead.  No clue what will happen to it.

**Comment by slundberg** [comment]
I agree a case insensitive FS is a mistake for OSX. As for the pull request, you have this code as GPLv2 and Clustering is under MIT, it might make sense to have this at MIT as well to allows things to be merged.

**Comment by slundberg** [comment]
BTW. Nice package. I was glad to find a pure Julia version of hierarchical clustering so I could share code using clustering without requiring R or Python integration installed.

**Comment by davidavdav** [comment]
I submitted a PR to a MIT package so I assume that the code in the PR
automatically  becomes MIT licensed.

---david

sent from a mobile Linux os.
Op 23 jun. 2015 17:28 schreef "Scott Lundberg" notifications@github.com:

**Comment by slundberg** [comment]
Makes sense, given you are the sole author.

**Comment by davidavdav** [comment]
If you want to run the code under MIT, maybe you can pressure the Clustering.jl maintainers to merge the the [PR](https://github.com/JuliaStats/Clustering.jl/pull/32)...  Then at least GPLv2 is good for something...

**Pull request merged**
