### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by slundberg**
I noticed that hclust() on a 3x3 matrix failed intermittently, so I added some unit tests that checked everything >= 4x4. These tests run the methods against R output for :complete, :average, and :single, and also use a default Julia TravisCI setup.

I also added an `@assert` for small matrices, if failing on small matrices is not intended that needs to be removed once the code is updated.

### CODE REVIEW

**Comment by slundberg** [comment]
I noticed that you got HClust merged into Clustering, and also saw that merge had some unit test related files. What do you think I should do with this? I think it is important to have unit tests that can be run by travis, and also add this assert. Perhaps I should do a PR on Clustering?

**Comment by davidavdav** [comment]
Hi Scott, 

Thanks for the testing infrastructure---it looks a lot better.  I understand the generated examples are fixed?

In what way do the 3x3 distance matrices fail the test?  Does the algorithm not end, or is the answer wrong, or is the answer not the same as the R answer?

I think you should pack this as a PR to clustering.  It might take a while before it gets accepted.

**Comment by slundberg** [comment]
Right the generated examples are fixed, I included the R file that generated them just as documentation.

It crashes with an out of bounds error. Try running (without the assert I added):

``` julia
using HClust
D = [
    0.74 0.99 0.99;
    0.99 0.74 0.98;
    0.99 0.98 0.74;
]
hclust(D, :complete)
```

I'll make this a PR to clustering

**Comment by davidavdav** [comment]
Yes, this is a bug all right.  Thanks for spotting it.  I know I am just going to hate tracking the boundary checking with base-1 indexing, but luckily it goes wrong with `N=3` and not with `N=1992` or so...

**Comment by davidavdav** [comment]
Mmm.  I have a trivial fix for `N<4`, but now found an example going wrong for `N=4`, so it really is more serious.  (There are some conditions `i>3` in `hclust2()`, so I first though `N=3` was a special case.)  

``` julia
D = [0.03371388 1.386249 2.039603 1.085455
        1.386249 0.01628432 0.004598792 0.07319126
        2.039603 0.004598792 0.7787556 0.253046
        1.085455 0.07319126 0.253046 0.002650744]
```

**Comment by davidavdav** [comment]
Hi Scott, 

It look like the culprit was in [this line](https://github.com/davidavdav/HClust.jl/blob/a5e52a5c478ec921176ffc0311aaebee62791782/src/main.jl#L305).  A stack for which I didn't reserve enough memory---the punishment for not using a stack I suppose.  

Now there are several options.  Github is all about social network statistics, so the people prefer single commits to keep the number-of-commits statistics clean---it usually takes me a few iterations of little requests about a PR before it is accepted, and then I have to squash the result to make the number-of-commits 1.  

One option is that you do a PR to _my_ Clustering.jl, and I will merge and apply the fix there and do a two-commit PR to the main Clustering guys.  This way, I hope, your contribution will be registered as such on Github. 

Another option is that you submit the PR to the main Clustering, and wait for an accept, and then I can fix it, and wait for an accept.  That seems slower.

**Comment by slundberg** [comment]
Thanks for the fix! Glad you were able to isolate it. I already packaged up the contents of this PR (and another bug fix) and sent them to Clustering.jl. I did this before you found that the bug effected more than just 3 variable clusterings, so it has already been merged and released. So I think the best bet would be for you to send a PR to Clustering with this bug fix. All of my contributions are already in Clustering.jl so you don't need to worry about them.

**Comment by slundberg** [comment]
...then Clustering v0.4.1 could be this bug fix.

**Pull request merged**
